Restaurant.create(name: 'Big Mama', address: 'Hotel de ville 2', category: 'french')
Restaurant.create(name: 'Il Casolare', address: 'Frankelufer 22', category: 'italian')
Restaurant.create(name: 'Happy Noulles', address: 'Hotel de ville 5', category: 'chinese')
Restaurant.create(name: 'Burger King', address: 'Bernauer Str', category: 'belgian')
Restaurant.create(name: 'Pink Mama', address: 'Hotel de ville 44', category: 'japanese')
Restaurant.create(name: 'Jimmy´s', address: 'G. Murat', category: 'italian')
